### PR TITLE
Troubleshooting permissions issue

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?
Related to https://github.com/jhudsl/OTTR_Template/issues/628

### CODE REVIEW

**Comment by cansavvy** [comment]
@RickSlc can you make sure that this repositories settings are allowing github actions to run? See instructions here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run

**Comment by cansavvy** [comment]
Can you also check if your settings underneath Settings > Actions look like this: 
Screen Shot 2023-04-05 at 11 41 40 AM

@RickSlc

**Comment by cansavvy** [comment]
@RickSlc Im seeing this appears to have worked. Did you change any settings?

**Comment by RickSlc** [comment]
Yes, it was the settings in the image that you sent, the Workflow
Permissions under the Settings/Actions/General. Now I am looking through
the real errors.

Thanks!

**Comment by cansavvy** [comment]
Thanks for letting me figure out this problem! I'm going to add this to our documentation! Thanks @RickSlc !

**Pull request closed without merging**
